services:
   db:
      image: postgres:16.2
      restart: always
      ports:
         - 5432:5432
      environment:
         - POSTGRES_PASSWORD=password
         - POSTGRES_USER=username
         - POSTGRES_DB=database
      volumes:
         - postgres_data:/var/lib/postgresql/data
volumes:
   postgres_data:
